// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASv7ysQ7-oGdy9kgaUkS1i6IwmGK8XnnA',
    appId: '1:323316501849:web:ca19b8f7ef6e89ea8a9048',
    messagingSenderId: '323316501849',
    projectId: 'mietbewertung-ddf4a',
    authDomain: 'mietbewertung-ddf4a.firebaseapp.com',
    databaseURL: 'https://mietbewertung-ddf4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mietbewertung-ddf4a.firebasestorage.app',
    measurementId: 'G-CCXBBX5SWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zw6KctOQGXDM6GfFhXZAdiwgJK9evqo',
    appId: '1:323316501849:android:abeabb3eea6f771a8a9048',
    messagingSenderId: '323316501849',
    projectId: 'mietbewertung-ddf4a',
    databaseURL: 'https://mietbewertung-ddf4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mietbewertung-ddf4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9TX5IyXlpnn7HDKmPGSPGwFudJESMCVo',
    appId: '1:323316501849:ios:d67c5db7b12208878a9048',
    messagingSenderId: '323316501849',
    projectId: 'mietbewertung-ddf4a',
    databaseURL: 'https://mietbewertung-ddf4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mietbewertung-ddf4a.firebasestorage.app',
    iosBundleId: 'com.example.immoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9TX5IyXlpnn7HDKmPGSPGwFudJESMCVo',
    appId: '1:323316501849:ios:d67c5db7b12208878a9048',
    messagingSenderId: '323316501849',
    projectId: 'mietbewertung-ddf4a',
    databaseURL: 'https://mietbewertung-ddf4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mietbewertung-ddf4a.firebasestorage.app',
    iosBundleId: 'com.example.immoApp',
  );
}
